Repository Team-Nogari/Huhoe, pull requests merged in 2022-05, with the labels that each got.

#24 DetailViewModel 구현
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Huhoe/Huhoe/Data/Data Source/DefaultCoinPriceHistoryDataSource.swift
  Huhoe/Huhoe/Data/Repositories/DefaultCandlestickRepository.swift
  Huhoe/Huhoe/Data/Repositories/DefaultTransactionWebSocketRepository.swift
  Huhoe/Huhoe/Domain/Interfaces/Repositories/CandlestickRepository.swift
  Huhoe/Huhoe/Domain/UseCases/CoinDetailUseCase.swift
  Huhoe/Huhoe/Domain/UseCases/CoinListUseCase.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/CoinHistoryCell.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/CoinHistoryCell.xib
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/ViewModel/CoinHistoryItem.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/ViewModel/HuhoeDetailViewModel.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/Base.lproj/HuhoeMainViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/CoinListCell.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/MoneyTextField.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/ViewModel/CoinInfoItem.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/ViewModel/HuhoeMainViewModel.swift
  Huhoe/Huhoe/Resource/Assets.xcassets/testImage.imageset/Contents.json
  Huhoe/Huhoe/Resource/Assets.xcassets/testImage.imageset/testImage.png
  Huhoe/Huhoe/Util/Array+extension.swift
  Huhoe/Huhoe/Util/Double+extension.swift
  Huhoe/Huhoe/Util/Observable+extension.swift
  Huhoe/Huhoe/Util/String+extension.swift
  Huhoe/Huhoe/Util/UIFont+extension.swift
Labels: feat, UI

#25 차트 및 플로팅 뷰 구현
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe/Data/Network/HTTP/HttpNetwork.swift
  Huhoe/Huhoe/Data/Repositories/DefaultTickerRepository.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/ChartImageView.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/ChartPriceAndDateView.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/ChartScrollView.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/ViewModel/HuhoeDetailViewModel.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
  Huhoe/Huhoe/Util/Date+extension.swift
Labels: bug, feat, fix, UI, refactor

#29 Chart 관련 로직 및 바인딩 Refactoring
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/ChartScrollView.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/ViewModel/ChartInformation.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/ViewModel/ChartPriceAndDateViewInformation.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/ViewModel/HuhoeDetailViewModel.swift
  Huhoe/Huhoe/Util/Double+extension.swift
Labels: refactor

#31 과거 월별 코인 손익 컬렉션뷰 아이템 바인딩
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/ViewModel/HuhoeDetailViewModel.swift
Labels: feat, UI

#39 메인화면 -> 상세화면 데이터 전달 구현
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/ViewModel/HuhoeDetailViewModel.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/CoinListCell.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/ViewModel/HuhoeMainViewModel.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/ViewModel/SelectedCoinInformation.swift
  Huhoe/Huhoe/Util/Double+extension.swift
  Huhoe/Huhoe/Util/HuhoeDateFormatter.swift
  Huhoe/Huhoe/Util/NSMutableAttributedString+extension.swift
  Huhoe/Huhoe/Util/String+extension.swift
Labels: bug, feat, fix, UI, refactor

#40 코인 심볼 현지화 업데이트
  Huhoe/Huhoe/Resource/en.lproj/Localizable.strings
  bithumb_localization_crawling.py
Labels: feat, UI

#41 커스텀 폰트 및 Accessibility 적용
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Huhoe/Huhoe/Presentation/Scene/Common/CustomDynamicFont.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/ChartPriceAndDateView.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/CoinHistoryCell.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/CoinHistoryCell.xib
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/Base.lproj/HuhoeMainViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/CoinListCell.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/CoinListCell.xib
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/MoneyTextField.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/ViewModel/HuhoeMainViewModel.swift
  Huhoe/Huhoe/Resource/Info.plist
  Huhoe/Huhoe/Resource/KOHIBaeum.ttf
  Huhoe/Huhoe/Util/NSMutableAttributedString+extension.swift
  Huhoe/Huhoe/Util/UIFont+extension.swift
Labels: bug, feat, fix, UI, refactor

#43 상세화면 코인별 날짜 최소 값 설정
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/Base.lproj/HuhoeMainViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/DatePickerViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
  Huhoe/Huhoe/Util/HuhoeDateFormatter.swift
Labels: feat

#46 Activity Indicator 구현
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Huhoe/Huhoe/Data/Repositories/DefaultTickerRepository.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
  Huhoe/Huhoe/Resource/Assets.xcassets/ButtonColor.colorset/Contents.json
  Huhoe/Huhoe/Resource/Assets.xcassets/indicator.dataset/Contents.json
  Huhoe/Huhoe/Resource/Assets.xcassets/indicator.dataset/indicatorDark.json
  Huhoe/Huhoe/Resource/Assets.xcassets/testImage.imageset/Contents.json
  Huhoe/Huhoe/Resource/Assets.xcassets/testImage.imageset/testImage.png
Labels: feat, UI

#48 상세 화면 코인 과거 데이터 못 불러오는 버그 수정
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
Labels: bug, fix

#50 앱 아이콘 수정
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Huhoe/Huhoe/Resource/Assets.xcassets/ButtonColor.colorset/Contents.json
Labels: UI

#52 LaunchScreen 앱 로고 및 백그라운드컬러 구현
  Huhoe/Huhoe/Application/AppDelegate.swift
  Huhoe/Huhoe/Resource/Assets.xcassets/AppLogo.imageset/AppLogo.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppLogo.imageset/Contents.json
  Huhoe/Huhoe/Resource/Base.lproj/LaunchScreen.storyboard
Labels: feat, UI

#54 AssistViewController 구현
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe/Application/AppDelegate.swift
  Huhoe/Huhoe/Application/SceneDelegate.swift
  Huhoe/Huhoe/Data/Repositories/DefaultTickerRepository.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeAssist/HuhoeAssistPageViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeAssist/HuhoeAssistViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeAssist/HuhoeAssistViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/Base.lproj/HuhoeMainViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
  Huhoe/Huhoe/Resource/Assets.xcassets/AssistPage/Contents.json
  Huhoe/Huhoe/Resource/Assets.xcassets/AssistPage/FirstAssistPage.imageset/Contents.json
  Huhoe/Huhoe/Resource/Assets.xcassets/AssistPage/FirstAssistPage.imageset/FirstAssistPage.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AssistPage/SecondAssistPage.imageset/Contents.json
  Huhoe/Huhoe/Resource/Assets.xcassets/AssistPage/SecondAssistPage.imageset/SecondAssistPage.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AssistPage/ThirdAssistPage.imageset/Contents.json
  Huhoe/Huhoe/Resource/Assets.xcassets/AssistPage/ThirdAssistPage.imageset/ThirdAssistPage.png
Labels: feat, UI

#56 가격 value 변경 (시가 -> 종가)
  Huhoe/Huhoe/Data/NetworkDTO/HTTP+DataMapping/CandlestickResponseDTO+Mapping.swift
  Huhoe/Huhoe/Data/NetworkDTO/HTTP+DataMapping/TransactionResponseDTO+Mapping.swift
Labels: bug, fix

#59 네트워크 요청 실패 시 얼럿 띄우기
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
  Huhoe/Huhoe/Util/UIView+extension.swift
Labels: fix

#60 네트워크 요청 실패 상황 대비하여 얼럿 추가
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
  Huhoe/Huhoe/Util/UIView+extension.swift
Labels: feat, fix

#64 투자금 입력 텍스트 필드 개선
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe.xcodeproj/xcshareddata/xcschemes/Huhoe.xcscheme
  Huhoe/Huhoe/Presentation/Scene/Common/HuhoeKeyboardView.swift
  Huhoe/Huhoe/Presentation/Scene/Common/HuhoeKeyboardView.xib
  Huhoe/Huhoe/Presentation/Scene/HuhoeAssist/HuhoeAssistPageViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeAssist/HuhoeAssistViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeAssist/HuhoeAssistViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/Base.lproj/HuhoeMainViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
Labels: refactor

#65 튜토리얼 화면 이미지 변경(해상도 Up)
  Huhoe/Huhoe/Resource/Assets.xcassets/AssistPage/FirstAssistPage.imageset/FirstAssistPage.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AssistPage/SecondAssistPage.imageset/SecondAssistPage.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AssistPage/ThirdAssistPage.imageset/ThirdAssistPage.png
Labels: UI, refactor

#67 상세화면 성능 개선
  Huhoe/Huhoe.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Huhoe/Huhoe/Data/NetworkDTO/HTTP+DataMapping/CandlestickResponseDTO+Mapping.swift
  Huhoe/Huhoe/Domain/Entities/CoinPriceHistory.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/ViewModel/HuhoeDetailViewModel.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/ViewModel/HuhoeMainViewModel.swift
Labels: bug, fix

#75 키보드 clear 버튼 구현 #69
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Huhoe/Huhoe/Presentation/Scene/Common/HuhoeKeyboardView.swift
  Huhoe/Huhoe/Presentation/Scene/Common/HuhoeKeyboardView.xib
Labels: feat, UI

#76 1.6.1 Release
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Huhoe/Huhoe/Presentation/Scene/Common/HuhoeKeyboardView.swift
  Huhoe/Huhoe/Presentation/Scene/Common/HuhoeKeyboardView.xib
Labels: feat, UI

#78 전반적인 코드 컨벤션 개선 및 성능 개선
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Huhoe/Huhoe/Data/API/TickerNetwork.swift
  Huhoe/Huhoe/Data/API/TransactionHistoryNetwork.swift
  Huhoe/Huhoe/Data/Data Source/DefaultCoinPriceHistoryDataSource.swift
  Huhoe/Huhoe/Data/Data Source/DefaultTickerDataSource.swift
  Huhoe/Huhoe/Data/Data Source/DefaultTransactionHistoryDataSource.swift
  Huhoe/Huhoe/Data/NetworkDTO/Websocket/TransactionWebSocketResponseDTO.swift
  Huhoe/Huhoe/Data/Repositories/DefaultTickerRepository.swift
  Huhoe/Huhoe/Data/Repositories/DefaultTransactionHistoryRepository.swift
  Huhoe/Huhoe/Data/Repositories/DefaultTransactionWebSocketRepository.swift
  Huhoe/Huhoe/Domain/Entities/RealTimeCoinPrice.swift
  Huhoe/Huhoe/Domain/Interfaces/Repositories/CandlestickRepository.swift
  Huhoe/Huhoe/Domain/Interfaces/Repositories/TransactionWebSocketRepository.swift
  Huhoe/Huhoe/Domain/UseCases/CoinDetailUseCase.swift
  Huhoe/Huhoe/Domain/UseCases/CoinListUseCase.swift
  Huhoe/Huhoe/Extension/Array+extension.swift
  Huhoe/Huhoe/Extension/Date+extension.swift
  Huhoe/Huhoe/Extension/Double+extension.swift
  Huhoe/Huhoe/Extension/NSMutableAttributedString+extension.swift
  Huhoe/Huhoe/Extension/Observable+extension.swift
  Huhoe/Huhoe/Extension/Result+extension.swift
  Huhoe/Huhoe/Extension/String+extension.swift
  Huhoe/Huhoe/Extension/UIFont+extension.swift
  Huhoe/Huhoe/Extension/UIView+extension.swift
  Huhoe/Huhoe/Presentation/Scene/Common/View/CustomDynamicFont.swift
  Huhoe/Huhoe/Presentation/Scene/Common/View/DatePickerViewController.swift
  Huhoe/Huhoe/Presentation/Scene/Common/View/HuhoeKeyboardView.swift
  Huhoe/Huhoe/Presentation/Scene/Common/View/HuhoeKeyboardView.xib
  Huhoe/Huhoe/Presentation/Scene/Common/ViewModel/ViewModel.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeAssist/HuhoeAssistPageViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeAssist/HuhoeAssistViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/ChartImageView.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/ChartPriceAndDateView.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/ChartScrollView.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/CoinHistoryCell.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/ViewModel/HuhoeDetailViewModel.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/CoinListCell.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/CoinListCell.xib
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/MoneyTextField.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/ViewModel/HuhoeMainViewModel.swift
  Huhoe/Huhoe/Util/Double+extension.swift
  Huhoe/Huhoe/Util/UIFont+extension.swift
  Huhoe/Huhoe/Utilities/HuhoeDateFormatter.swift
  Huhoe/Huhoe/Utilities/HuhoeNumberFormatter.swift
  README.md
Labels: refactor

#81 network observable stream 분기되지 않도록 로직 수정
  Huhoe/Huhoe/Domain/UseCases/CoinListUseCase.swift
Labels: fix
