Repository Team-Nogari/Huhoe, pull requests merged in 2022-04, with the labels that each got.

#5 REST API 구현
  .gitignore
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe/Application/SceneDelegate.swift
  Huhoe/Huhoe/Data/API/CandlestickNetwork.swift
  Huhoe/Huhoe/Data/API/TickerNetwork.swift
  Huhoe/Huhoe/Data/API/TransactionHistoryNetwork.swift
  Huhoe/Huhoe/Data/APIPath.swift
  Huhoe/Huhoe/Data/Network/Error/NetworkError.swift
  Huhoe/Huhoe/Data/Network/Network.swift
  Huhoe/Huhoe/Data/Network/NetworkProvider.swift
  Huhoe/Huhoe/Data/Network/Protocol/URLSeesionProtocol.swift
Labels: feat

#4 네트워크 DTO 구현
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe/Data/NetworkDTO/DataMapping/CandlestickResponseDTO+Mapping.swift
  Huhoe/Huhoe/Data/NetworkDTO/DataMapping/TickerAllResponseDTO+Mapping.swift
  Huhoe/Huhoe/Data/NetworkDTO/DataMapping/TransactionResponseDTO+Mapping.swift
  Huhoe/Huhoe/Domain/Entities/CoinPriceHistory.swift
  Huhoe/Huhoe/Domain/Entities/Ticker.swift
  Huhoe/Huhoe/Domain/Entities/TickerResponse.swift
  Huhoe/Huhoe/Domain/Entities/Transaction.swift
  Huhoe/Huhoe/Util/String+extension.swift
Labels: feat

#7 repositories 구현
  .gitignore
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Huhoe/Huhoe/Data/API/CandlestickNetwork.swift
  Huhoe/Huhoe/Data/API/TickerNetwork.swift
  Huhoe/Huhoe/Data/API/TransactionHistoryNetwork.swift
  Huhoe/Huhoe/Data/APIPath.swift
  Huhoe/Huhoe/Data/Network/Network.swift
  Huhoe/Huhoe/Data/Network/Protocol/URLSeesionProtocol.swift
  Huhoe/Huhoe/Data/NetworkDTO/DataMapping/TransactionResponseDTO+Mapping.swift
  Huhoe/Huhoe/Data/Repositories/DefaultCandlestickRepository.swift
  Huhoe/Huhoe/Data/Repositories/DefaultTickerRepository.swift
  Huhoe/Huhoe/Data/Repositories/DefaultTransactionHistoryRepository.swift
  Huhoe/Huhoe/Domain/Interfaces/Repositories/CandlestickRepository.swift
  Huhoe/Huhoe/Domain/Interfaces/Repositories/TickerRepository.swift
  Huhoe/Huhoe/Domain/Interfaces/Repositories/TransactionHistoryRepository.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
Labels: feat

#11 Main View 구현
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe/Data/API/CandlestickNetwork.swift
  Huhoe/Huhoe/Data/API/TransactionHistoryNetwork.swift
  Huhoe/Huhoe/Data/Data Source/DefaultCoinPriceHistoryDataSource.swift
  Huhoe/Huhoe/Data/Data Source/DefaultTickerDataSource.swift
  Huhoe/Huhoe/Data/Data Source/DefaultTransactionHistoryDataSource.swift
  Huhoe/Huhoe/Data/NetworkDTO/DataMapping/CandlestickResponseDTO+Mapping.swift
  Huhoe/Huhoe/Data/Repositories/DefaultCandlestickRepository.swift
  Huhoe/Huhoe/Data/Repositories/DefaultTickerRepository.swift
  Huhoe/Huhoe/Data/Repositories/DefaultTransactionHistoryRepository.swift
  Huhoe/Huhoe/Domain/Entities/CoinPriceHistory.swift
  Huhoe/Huhoe/Domain/Interfaces/Repositories/CandlestickRepository.swift
  Huhoe/Huhoe/Domain/Interfaces/Repositories/TickerRepository.swift
  Huhoe/Huhoe/Domain/Interfaces/Repositories/TransactionHistoryRepository.swift
  Huhoe/Huhoe/Domain/UseCases/CoinListUseCase.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/Base.lproj/HuhoeMainViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/CoinListCell.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/CoinListCell.xib
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/DatePickerViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/MoneyTextField.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/ViewModel/CoinInfoItem.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/ViewModel/HuhoeMainViewModel.swift
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  Huhoe/Huhoe/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Huhoe/Huhoe/Resource/Assets.xcassets/ButtonColor.colorset/Contents.json
  Huhoe/Huhoe/Resource/Assets.xcassets/CoinCellBackgroundColor.colorset/Contents.json
  Huhoe/Huhoe/Resource/en.lproj/Localizable.strings
  Huhoe/Huhoe/Util/Date+extension.swift
  Huhoe/Huhoe/Util/String+extension.swift
Labels: feat, fix, UI, refactor

#14 디테일 화면 구현
  Huhoe/Huhoe.xcodeproj/project.pbxproj
  Huhoe/Huhoe/Data/Repositories/DefaultTickerRepository.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/CoinHistoryCell.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/CoinHistoryCell.xib
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/Base.lproj/HuhoeMainViewController.storyboard
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/CoinListCell.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/CoinListCell.xib
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
Labels: feat, UI

#18 네비게이션 바 버그 개선
  Huhoe/Huhoe/Presentation/Scene/HuhoeDetail/View/HuhoeDetailViewController.swift
  Huhoe/Huhoe/Presentation/Scene/HuhoeMain/View/HuhoeMainViewController.swift
Labels: bug, fix
